---
- !ruby/object:MenuItem 
  controller: elaine
  text: Elaine
  action: index
  items: []
  - !ruby/object:MenuItem 
    text: Home page
    controller: elaine
    action: index
  - !ruby/object:MenuItem 
    text: Personal info<br/><span class="description">Edit your details in Elaine</span>
    controller: user
    action: edit
  - !ruby/object:MenuItem 
    text: Elaine Known Issues<br/><span class="description">..if you have a problem</span>
    controller: elaine
    action: issues
  - !ruby/object:MenuItem 
    text: Elaine TODO<br/><span class="description">Things to be done</span>
    controller: elaine
    action: todo
  - !ruby/object:MenuItem 
    text: Log out
    controller: user
    action: logout    
- !ruby/object:MenuItem 
  controller: playlists
  text: Playlist
  action: list
  items: []
  - !ruby/object:MenuItem 
    text: Playlist<br/><span class="description">View/Edit Playlist</span>
    controller: playlists
    action: list
  - !ruby/object:MenuItem 
    text: Timeline<br/><span class="description">Observe Playlist as a Timeline</span>
    controller: playlists
    action: timeline
  - !ruby/object:MenuItem 
    text: Broadcast log<br/><span class="description">View broadcast log</span>
    controller: broadcast_logs
    action: list
- !ruby/object:MenuItem 
  controller: programs
  action: list
  items: []
  - !ruby/object:MenuItem 
    text: List Programs
    controller: programs
    action: list
  - !ruby/object:MenuItem 
    text: User's Programs
    controller: programs
    action: list_by_user
  - !ruby/object:MenuItem 
    text: New Program<br/><span class="description">Add a new program</span>
    controller: programs
    action: new
- !ruby/object:MenuItem 
  controller: events
  action: list
  items: []
  - !ruby/object:MenuItem 
    text: List Events
    controller: events
    action: list
  - !ruby/object:MenuItem 
    text: New Event<br/><span class="description">Add a new event</span>
    controller: events
    action: new
- !ruby/object:MenuItem 
  controller: tapes
  action: list
  items: []
  - !ruby/object:MenuItem 
    text: List Tapes
    controller: tapes
    action: list
  - !ruby/object:MenuItem 
    text: New Tape<br/><span class="description">Add a new tape</span>
    controller: tapes
    action: new
- !ruby/object:MenuItem 
  controller: vods
  action: list
  items: []
  - !ruby/object:MenuItem 
    text: List Vods
    controller: vods
    action: list
  - !ruby/object:MenuItem 
    text: List Vod Groups
    controller: vod_groups
    action: list
  - !ruby/object:MenuItem 
    text: List Vod Formats
    controller: vod_formats
    action: list
- !ruby/object:MenuItem 
  controller: user
  text: Admin
  action: list
  items: []
  - !ruby/object:MenuItem 
    text: Users
    controller: user
    action: list
  - !ruby/object:MenuItem 
    text: Permissions
    controller: permission
    action: list
  - !ruby/object:MenuItem 
    text: Roles
    controller: role
    action: list
