---
- !ruby/object:MenuItem 
  controller: playlists
  text: Playlist
  action: list
  items: []
  - !ruby/object:MenuItem 
    text: Playlist<br/><span class="description">View/Edit Playlist</span>
    controller: playlists
    action: list
  - !ruby/object:MenuItem 
    text: Timeline<br/><span class="description">Observe Playlist as a Timeline</span>
    controller: playlists
    action: timeline
- !ruby/object:MenuItem 
  controller: programs
  action: list
  items: []
  - !ruby/object:MenuItem 
    text: List Programs
    controller: programs
    action: list
  - !ruby/object:MenuItem 
    text: New Program<br/><span class="description">Add a new program</span>
    controller: programs
    action: new
- !ruby/object:MenuItem 
  controller: events
  action: list
  items: []
  - !ruby/object:MenuItem 
    text: List Events
    controller: events
    action: list
  - !ruby/object:MenuItem 
    text: New Event<br/><span class="description">Add a new event</span>
    controller: events
    action: new
- !ruby/object:MenuItem 
  controller: tapes
  action: list
  items: []
  - !ruby/object:MenuItem 
    text: List Tapes
    controller: tapes
    action: list
  - !ruby/object:MenuItem 
    text: New Tape<br/><span class="description">Add a new tape</span>
    controller: programs
    action: new
- !ruby/object:MenuItem 
  controller: user
  action: home
  items: []
  - !ruby/object:MenuItem 
    text: User Home
    controller: user
    action: home
  - !ruby/object:MenuItem 
    text: Edit<br/><span class="description">Edit your details in Elaine</span>
    controller: user
    action: edit
  - !ruby/object:MenuItem 
    text: Log out
    controller: user
    action: logout
- !ruby/object:MenuItem 
  controller: user
  text: Admin
  action: list
  items: []
  - !ruby/object:MenuItem 
    text: Users
    controller: user
    action: list
  - !ruby/object:MenuItem 
    text: Permissions
    controller: permission
    action: list
  - !ruby/object:MenuItem 
    text: Roles
    controller: roles
    action: list
